### ISSUE TITLE
Virustotal .exe scan 

### ISSUE THREAD

**Issue by Bukilan** [vorace3200/HalfSword-TimeControler#1]
https://www.virustotal.com/gui/file/a5a34c7c9c284d8bf2d32c18bc6542b3d94f6a59f40d1fe7ea6a6c06b0b44272?nocache=1

**Comment by Bukilan** [comment]
![image](https://github.com/user-attachments/assets/b7b1b120-a9fa-4ed9-80cb-86e5cf65257c)

**Comment by vorace3200** [comment]
Hello ! :)
I'm changing the game's memory, so I use WriteMemory and ReadMemory. As soon as you start using this kind of function, antivirus software doesn't like it. If you really want to be sure, you can take my code from the github and compile it yourself or you can grab the offsets to use it on your own software 🙃
